// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdh61f3N7S7IztM4e-H72KYjpLi7uFXbE',
    appId: '1:300260142579:web:2c91c2fa69ce03a2b7b686',
    messagingSenderId: '300260142579',
    projectId: 'app-project-7cc1a',
    authDomain: 'app-project-7cc1a.firebaseapp.com',
    storageBucket: 'app-project-7cc1a.firebasestorage.app',
    measurementId: 'G-11XWBDE0WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXgEaOuFN3fgqAZyz2MDidWrz-sAOZew',
    appId: '1:300260142579:android:87bf80bd67c83cfab7b686',
    messagingSenderId: '300260142579',
    projectId: 'app-project-7cc1a',
    storageBucket: 'app-project-7cc1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVxzRBbElhWcH8VuZBr2OO6bREV3D3yk',
    appId: '1:300260142579:ios:9aa452454ab77464b7b686',
    messagingSenderId: '300260142579',
    projectId: 'app-project-7cc1a',
    storageBucket: 'app-project-7cc1a.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbVxzRBbElhWcH8VuZBr2OO6bREV3D3yk',
    appId: '1:300260142579:ios:9aa452454ab77464b7b686',
    messagingSenderId: '300260142579',
    projectId: 'app-project-7cc1a',
    storageBucket: 'app-project-7cc1a.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdh61f3N7S7IztM4e-H72KYjpLi7uFXbE',
    appId: '1:300260142579:web:cfc6e4fcb45c576db7b686',
    messagingSenderId: '300260142579',
    projectId: 'app-project-7cc1a',
    authDomain: 'app-project-7cc1a.firebaseapp.com',
    storageBucket: 'app-project-7cc1a.firebasestorage.app',
    measurementId: 'G-6ZKDZBJS05',
  );
}
